# - name: Ensure myid is set in /kafka/myid
#   template:
#     src: myid
#     dest: "/kafka/myid"
#   notify: restart zookeeper
#   tags: zookeeper

- name: Creates directory /kafka/zookeeper
  file:
    path: /kafka/zookeeper
    state: directory

- name: Creates directory /etc/kafka/zookeeper
  file:
    path: /etc/kafka/zookeeper
    state: directory

- name: config zookeeper
  template:
    src: zookeeper.properties.j2
    dest: /etc/kafka/zookeeper.conf
    owner: root
    group: root
    mode: 644

- name: systemd start script
  template:
    src: zookeeper-systemd.j2
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
    mode: 644
  notify: start zookeeper
  tags: zookeeper
