- name: Ensure myid is set in {{ zk.data_dir }}/myid
  template:
    src: myid
    dest: "{{ zk.data_dir }}/myid"
  notify: restart zookeeper
  tags: zookeeper

- name: config zookeeper
  template:
    src: zookeeper.properties.j2
    dest: /kafka/config/zookeeper.service
    owner: root
    group: root
    mode: 644

- name: systemd start script
  template:
    src: zookeeper-systemd.j2
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
    mode: 644
  notify: start zookeeper
  tags: zookeeper
