apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres
data:
  postgresql.conf: |
    # Add settings for extensions here
    wal_level = logical
    max_wal_senders = 4
    max_replication_slots = 4
    listen_addresses = '*'  # Listen on all interfaces
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     trust
    host    all             all             0.0.0.0/0               md5
    host    all             all             ::/0                    md5 