---

- name: Change the hostname to our standard
  hostname:
    name="{{ inventory_hostname }}"
  when:
    ansible_fqdn != ansible_ssh_host

- name: Download distr Apache Kafka
  command: curl "https://downloads.apache.org/kafka/2.8.1/kafka_2.12-2.8.1.tgz" -o /tmp/kafka.tgz

- name: Creates repo directory
  file:
    path: /kafka
    state: directory

- name: Creates repo directory
  file:
    path: /tmp/zookeeper
    state: directory

- name: Creates directory /etc/kafka
  file:
    path: /etc/kafka
    state: directory

- name: Extract kafka.tgz into /tmp
  command: tar -xvzf /tmp/kafka.tgz -C /tmp/

- name: Delete distr Kafka
  command: rm -rf /tmp/kafka.tgz

- name: Copy to /kafka
  command: cp -a /tmp/kafka_2.12-2.8.1/. /kafka/
  become: True

- name: config myid1
  template:
    src: myid1.j2
    dest: /etc/kafka/myid
    owner: root
    group: root
    mode: 644
  when: inventory_hostname == "kafka1"

- name: config myid2
  template:
    src: myid2.j2
    dest: /etc/kafka/myid
    owner: root
    group: root
    mode: 644
  when: inventory_hostname == "kafka2"

- name: config myid3
  template:
    src: myid3.j2
    dest: /etc/kafka/myid
    owner: root
    group: root
    mode: 644
  when: inventory_hostname == "kafka3"

- name: Install Java
  yum:
    name: java
    state: latest