---
# tasks file for roles/kafka
- name: Copy file.role1 to host1
  copy: src=file.role1 dest=/somewhere/file
  when: inventory_hostname == "host1"

- name: Creates directory /var/kafka
  file:
    path: /var/kafka
    state: directory

- name: Creates directory /kafka/kafka-logs
  file:
    path: /kafka/kafka-logs
    state: directory

- name: Creates directory /tmp/kafka
  file:
    path: /tmp/kafka
    state: directory

- name: config kafka1
  template:
    src: kafka1-properties.j2
    dest: /etc/kafka/kafka.conf
    owner: root
    group: root
    mode: 644
  when: inventory_hostname == "kafka1"

- name: config kafka2
  template:
    src: kafka2-properties.j2
    dest: /etc/kafka/kafka.conf
    owner: root
    group: root
    mode: 644
  when: inventory_hostname == "kafka2"

- name: config kafka3
  template:
    src: kafka3-properties.j2
    dest: /etc/kafka/kafka.conf
    owner: root
    group: root
    mode: 644
  when: inventory_hostname == "kafka3"

- name: systemd start script
  template:
    src: kafka-systemd.j2
    dest: /etc/systemd/system/kafka.service
    owner: root
    group: root
    mode: 644
  notify: start kafka
  tags: kafka

- name: Restart service zookeeper
  service:
    name: zookeeper
    state: restarted
