apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-publisher-config
  namespace: postgres
data:
  postgresql.conf: |
    wal_level = logical
    max_replication_slots = 10
    max_wal_senders = 10
    max_worker_processes = 10
    max_logical_replication_workers = 8
    max_sync_workers_per_subscription = 4 