apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-replica
  namespace: postgres
spec:
  serviceName: postgres-replica
  replicas: 1
  selector:
    matchLabels:
      app: postgres-replica
  template:
    metadata:
      labels:
        app: postgres-replica
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: postgresdb
        volumeMounts:
        - name: postgres-replica-data
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
        - name: postgres-replica-config
          mountPath: /etc/postgresql/postgresql.conf
          subPath: postgresql.conf
      volumes:
      - name: postgres-replica-config
        configMap:
          name: postgres-replica-config
  volumeClaimTemplates:
  - metadata:
      name: postgres-replica-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-replica
  namespace: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-replica 